server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  mapper-locations: classpath:mapper/*.xml               # mapper映射文件
    
spring:
   application:
    name: BISP-PROVIDER
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/blog                   # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#   thymeleaf: 
#     cache: false
#     servlet:
#          content-type: text/html
#     check-template-location: true
#     mode: LEGACYHTML5　                             # 这个里面不是严格的html5规范　不设置仍然会报错
#     enabled: true
#     prefix: classpath:/templates/
#     suffix: .html
 
 
#feign:
#  hystrix:
#    enabled: true
 
pagehelper: 
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: bisp-provider-8001   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
    
    
info:
  app.name: BISP
  company.name: www.bisp.com
  build.artifactId: bisp-provider-main
  build.version: 0.0.1-SNAPSHOT
    